EmployeeDataCollectionApp/urls.py
"""EmployeeDataCollectionApp URL Configuration

"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mainApp.urls"))
]

urlpatterns += staticfiles_urlpatterns()

mainApp/urls.py
from django.urls import path
from .import views
app_name = "mainApp"

urlpatterns = [
	path("", views.EmployeeListView ,name="list-employees"),
	path("add-employee", views.AddEmployeeView, name="add-employee"),
	path("upload-excel-file", views.ExcelDataUploadView, name="upload-excel"),
	path("upload-logs", views.UploadLogsView, name="logs-employees"),

	path("login/", views.LoginView, name="login"),
	path("logout", views.Logout, name="logout")
]

mainApp/models.py
from django.db import models
import random

# Employee code is the required argument for creating supervisor
class Supervisors(models.Model):
	supervisor  		= models.CharField(max_length=100)

	def __str__(self):
		return self.supervisor
	
	class Meta:
		verbose_name_plural = "Supervisors"

class Employee(models.Model):
	first_name 			= models.CharField(max_length=100)
	middle_name			= models.CharField(max_length=100)
	date_of_graduation 	= models.CharField(max_length=100)
	date_of_employment  = models.CharField(max_length=100)
	position 			= models.CharField(max_length=100)
	salary 				= models.IntegerField()
	supervisors 		= models.ManyToManyField(Supervisors, blank=True)
	employee_code 		= models.CharField(max_length=6,blank=True, null=True)
	
	def save(self, *args, **kwargs):
		getThreeRandomNumbers   	  	= "".join(random.choice("0123456789") for i in range(3))
		generatedEmployeeCode  			= self.first_name[:1]+self.middle_name[:1]+'-'+getThreeRandomNumbers
		self.employee_code 				= generatedEmployeeCode
		super().save(*args, **kwargs)

	def __str__(self):
		return f"{self.first_name+self.middle_name}"

	class Meta:
		verbose_name_plural = "Employee Records"


class UploadLogs(models.Model):
	timestamp_of_upload 				= models.DateTimeField(auto_now_add=True)
	number_of_employee_records_uploaded = models.IntegerField()
	status 								= models.CharField(max_length=100)
	errors 								= models.CharField(max_length=100, blank=True, null=True)
	number_of_duplicate_entries 		= models.IntegerField()

	def __str__(self):
		return f"{self.status}"

	class Meta:
		verbose_name_plural = "Upload logs"

mainApp/views.py
import os
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .models import Employee, Supervisors, UploadLogs
from .backends import ValidateSupervisorCreation, UploadExcelAndValidation
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.
def LoginView(request):
	# Creating superuser
	if User.objects.filter(is_superuser=True, is_staff=True, username="admin").exists():
		pass
	else:
		admin_user   	= User.objects.create(username="admin", is_superuser=True, is_staff=True)
		admin_user.set_password("keypass")
		admin_user.save()


	if request.method=='POST':
		username 		= request.POST.get("username")
		password 		= request.POST.get("password")
		user 			= authenticate(request, username=username, password=password)

		if user is not None:
			login(request, user)
			return redirect('mainApp:list-employees')

		else:
			messages.error(request, "Please enter the correct username and password. Note that both fields may be case-sensitive")
			return render(request, 'login.html')

	return render(request, 'login.html')

@login_required
def Logout(request):
	logout(request)
	return redirect('/login')

@login_required
def EmployeeListView(request):
	employees  	= Employee.objects.all().order_by('first_name')
	context 	= {"employees":employees}
	return render(request, 'employee-list.html',context)

@login_required
def AddEmployeeView(request):
	employees 	= Employee.objects.all()
	context 	= {"employees":employees}
	
	# Taking form values on post
	if request.method =='POST':
		first_name    				=  request.POST.get('first_name')
		middle_name   				=  request.POST.get('middle_name')
		date_of_graduation     		=  request.POST.get('date_of_graduation')
		date_of_employment  		=  request.POST.get('date_of_employment')
		position					=  request.POST.get('position')
		salary						=  request.POST.get('salary')
		getSupervisors				=  request.POST.getlist('get_supervisor')
		
		try:
			employee 		= Employee.objects.create(
								first_name=first_name, middle_name=middle_name,
								date_of_graduation=date_of_graduation, 
								date_of_employment=date_of_employment, position=position,
								salary=salary)
			employee.save()

			# If no supervisor was selected
			if len(getSupervisors)==0:
				pass
			# If one or more supervisor(s) were selected
			else:
				for supervisor_code in getSupervisors:
					supervisor_key_name = ValidateSupervisorCreation(supervisor_code)
					
					# If the employee already have a supervisor account
					if Supervisors.objects.filter(supervisor=supervisor_key_name).exists():
						supervisor = Supervisors.objects.get(supervisor=supervisor_key_name)
						employee.supervisors.add(supervisor)

					# If the employee does not have a supervisor account
					else:
						supervisor = Supervisors.objects.create(supervisor=supervisor_key_name)
						supervisor.save()
						employee.supervisors.add(supervisor)

			saveLog 		= UploadLogs.objects.create(
								number_of_employee_records_uploaded= 1,
								status="Success", number_of_duplicate_entries=0)
			saveLog.save()

			messages.success(request, "Employee added successfully")
			return render(request, 'add-employee.html', context)

		except Exception as e:
			messages.error(request, str(e))
	return render(request, 'add-employee.html',context)

@login_required
def ExcelDataUploadView(request):
	if request.method == "POST":
		excel_file     			= request.FILES.get("employee_excel_file")
		# Getting filename and extension
		file_name, extension 	= os.path.splitext(excel_file.name)
				
		if '.xlsx' == extension:
			uploadAndCheck 		= UploadExcelAndValidation(excel_file)
			# Checking if any error occured
			if uploadAndCheck[2]==True:
				messages.error(request, uploadAndCheck[3])

			# Valid file
			else:
				messages.success(request, "Employee Data uploaded successfully")
				return render(request, 'excel-file-upload.html')
		
		# If file wasn't a '.xlsx'
		else:
			messages.error(request, "Invalid file upload, please upload an excel file")
			return render(request, 'excel-file-upload.html')

	return render(request, 'excel-file-upload.html')

@login_required
def UploadLogsView(request):
	logs 		= UploadLogs.objects.all()
	context 	= {"logs":logs}
	return render(request, 'logs.html', context)

mainApp/templates/add-employee.html
{% extends 'base.html' %}
{% load static %}
{% block dashboardActive %} active {% endblock %}
{% block content %}
	<div id="content">
                <div class="panel box-shadow-none content-header">
                  <div class="panel-body">
                    <div class="col-md-12">
                        <h3 class="animated fadeInLeft">Add Employee</h3>
                        <p class="animated fadeInDown">
                          Manual employee creation page
                        </p>
                    </div>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="col-md-12 panel">
                    <div class="col-md-12 panel-body" style="padding-bottom:30px;">
                      <div class="col-md-12">
                      	 {% if messages %}
                    		{% for message in messages %}
                        		<div  class="alert alert-{{message.tags }}" role="alert">
                            		{{message}}
                        		</div>
                    		{% endfor %}
                		{% endif %}    
                        <form method="POST" class="cmxform" id="signupForm">
                        	{% csrf_token %}
                          <div class="col-md-6">
                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                              <input type="text" name="first_name" class="form-text" id="validate_firstname" required>
                              <span class="bar"></span>
                              <label>First Name</label>
                            </div>

                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                              <input type="text" name="middle_name" class="form-text" id="validate_lastname"  required>
                              <span class="bar"></span>
                              <label>Middle Name</label>
                            </div>

                                                      

                            <div class="col-sm-12 padding-0" style="margin-bottom:40px !important;">
                                  <label>Select supervisor(s)</label><br>
                                  <select name="get_supervisor" class="form-control" multiple>
                                  	{% for employee in employees %}
                                    	<option value="{{employee.employee_code}}">{{employee}}</option>
                                    {% endfor %}
                                  </select>
                                </div>
                          </div>


                          <div class="col-md-6">
                          	<br>
                          	<label>Date of graduation</label><br>
	                        <div class="form-group form-animate-text">
	                          <input type="date" name="date_of_graduation" class="form-text dateAnimate" required>
	                          <span class="bar"></span>
	                        </div>

	                        <label>Date of employment</label><br>
	                        <div class="form-group form-animate-text">
	                          <input type="date" name="date_of_employment" class="form-text dateAnimate" required>
	                          <span class="bar"></span>
	                        </div>

	                        <div class="form-group form-animate-text" style="margin-top:40px !important;">
                              <input type="text" class="form-text" id="validate_password" name="position" required>
                              <span class="bar"></span>
                              <label>Position</label>
                            </div>

                            <div class="form-group form-animate-text" style="margin-top:40px !important;">
                              <input type="number" class="form-text" id="validate_password" name="salary" required>
                              <span class="bar"></span>
                              <label>Salary</label>
                            </div>

                           

                          </div> 
                          <div class="col-md-12">
                              <input class="submit btn btn-success" type="submit" value="Submit">
                        </div>
                      </form>

                    </div>
                  </div>
                </div>
              </div>

{% endblock %}

{% block javascript %}

<script type="text/javascript">
  $(document).ready(function(){

    $("#signupForm").validate({
      errorElement: "em",
      errorPlacement: function(error, element) {
        $(element.parent("div").addClass("form-animate-error"));
        error.appendTo(element.parent("div"));
      },
      success: function(label) {
        $(label.parent("div").removeClass("form-animate-error"));
      },
      rules: {
        validate_firstname: "required",
        validate_lastname: "required",
        validate_username: {
          required: true,
          minlength: 2
        },
        validate_password: {
          required: true,
          minlength: 5
        },
        validate_confirm_password: {
          required: true,
          minlength: 5,
          equalTo: "#validate_password"
        },
        validate_email: {
          required: true,
          email: true
        },
        validate_agree: "required"
      },
      messages: {
        validate_firstname: "Please enter your firstname",
        validate_lastname: "Please enter your lastname",
        validate_username: {
          required: "Please enter a username",
          minlength: "Your username must consist of at least 2 characters"
        },
        validate_password: {
          required: "Please provide a password",
          minlength: "Your password must be at least 5 characters long"
        },
        validate_confirm_password: {
          required: "Please provide a password",
          minlength: "Your password must be at least 5 characters long",
          equalTo: "Please enter the same password as above"
        },
        validate_email: "Please enter a valid email address",
        validate_agree: "Please accept our policy"
      }
    });

    // propose username by combining first- and lastname
    $("#username").focus(function() {
      var firstname = $("#firstname").val();
      var lastname = $("#lastname").val();
      if (firstname && lastname && !this.value) {
        this.value = firstname + "." + lastname;
      }
    });


    $('.mask-date').mask('00/00/0000');
    $('.mask-time').mask('00:00:00');
    $('.mask-date_time').mask('00/00/0000 00:00:00');
    $('.mask-cep').mask('00000-000');
    $('.mask-phone').mask('0000-0000');
    $('.mask-phone_with_ddd').mask('(00) 0000-0000');
    $('.mask-phone_us').mask('(000) 000-0000');
    $('.mask-mixed').mask('AAA 000-S0S');
    $('.mask-cpf').mask('000.000.000-00', {reverse: true});
    $('.mask-money').mask('000.000.000.000.000,00', {reverse: true});
    $('.mask-money2').mask("#.##0,00", {reverse: true});
    $('.mask-ip_address').mask('0ZZ.0ZZ.0ZZ.0ZZ', {
      translation: {
        'Z': {
          pattern: /[0-9]/, optional: true
        }
      }
    });
    $('.mask-ip_address').mask('099.099.099.099');
    $('.mask-percent').mask('##0,00%', {reverse: true});
    $('.mask-clear-if-not-match').mask("00/00/0000", {clearIfNotMatch: true});
    $('.mask-placeholder').mask("00/00/0000", {placeholder: "__/__/____"});
    $('.mask-fallback').mask("00r00r0000", {
      translation: {
        'r': {
          pattern: /[\/]/, 
          fallback: '/'
        }, 
        placeholder: "__/__/____"
      }
    });
    $('.mask-selectonfocus').mask("00/00/0000", {selectOnFocus: true});

    var options =  {onKeyPress: function(cep, e, field, options){
      var masks = ['00000-000', '0-00-00-00'];
      mask = (cep.length>7) ? masks[1] : masks[0];
      $('.mask-crazy_cep').mask(mask, options);
    }};

    $('.mask-crazy_cep').mask('00000-000', options);


    var options2 =  { 
      onComplete: function(cep) {
        alert('CEP Completed!:' + cep);
      },
      onKeyPress: function(cep, event, currentField, options){
        console.log('An key was pressed!:', cep, ' event: ', event, 
          'currentField: ', currentField, ' options: ', options);
      },
      onChange: function(cep){
        console.log('cep changed! ', cep);
      },
      onInvalid: function(val, e, f, invalid, options){
        var error = invalid[0];
        console.log ("Digit: ", error.v, " is invalid for the position: ", error.p, ". We expect something like: ", error.e);
      }
    };

    $('.mask-cep_with_callback').mask('00000-000', options2);

    var SPMaskBehavior = function (val) {
      return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
    },
    spOptions = {
      onKeyPress: function(val, e, field, options) {
        field.mask(SPMaskBehavior.apply({}, arguments), options);
      }
    };

    $('.mask-sp_celphones').mask(SPMaskBehavior, spOptions);



    var slider = document.getElementById('noui-slider');
    noUiSlider.create(slider, {
      start: [20, 80],
      connect: true,
      range: {
        'min': 0,
        'max': 100
      }
    });

    var slider = document.getElementById('noui-range');
    noUiSlider.create(slider, {
                        start: [ 20, 80 ], // Handle start position
                        step: 10, // Slider moves in increments of '10'
                        margin: 20, // Handles must be more than '20' apart
                        connect: true, // Display a colored bar between the handles
                        direction: 'rtl', // Put '0' at the bottom of the slider
                        orientation: 'vertical', // Orient the slider vertically
                        behaviour: 'tap-drag', // Move handle on tap, bar is draggable
                        range: { // Slider can select '0' to '100'
                        'min': 0,
                        'max': 100
                      },
                        pips: { // Show a scale with the slider
                          mode: 'steps',
                          density: 2
                        }
                      });



    $(".select2-A").select2({
      placeholder: "Select a state",
      allowClear: true
    });

    $(".select2-B").select2({
      tags: true
    });

    $("#range1").ionRangeSlider({
      type: "double",
      grid: true,
      min: -1000,
      max: 1000,
      from: -500,
      to: 500
    });

    $('.dateAnimate').bootstrapMaterialDatePicker({ weekStart : 0, time: false,animation:true});
    $('.date').bootstrapMaterialDatePicker({ weekStart : 0, time: false});
    $('.time').bootstrapMaterialDatePicker({ date: false,format:'HH:mm',animation:true});
    $('.datetime').bootstrapMaterialDatePicker({ format : 'dddd DD MMMM YYYY - HH:mm',animation:true});
    $('.date-fr').bootstrapMaterialDatePicker({ format : 'DD/MM/YYYY HH:mm', lang : 'fr', weekStart : 1, cancelText : 'ANNULER'});
    $('.min-date').bootstrapMaterialDatePicker({ format : 'DD/MM/YYYY HH:mm', minDate : new Date() });


    $(".dial").knob({
      height:80
    });

    $('.dial1').trigger(
     'configure',
     {
       "min":10,
       "width":80,
       "max":80,
       "fgColor":"#FF6656",
       "skin":"tron"
     }
     );

    $('.dial2').trigger(
     'configure',
     {

       "width":80,
       "fgColor":"#FF6656",
       "skin":"tron",
       "cursor":true
     }
     );

    $('.dial3').trigger(
     'configure',
     {

       "width":80,
       "fgColor":"#27C24C",
     }
     );
  });
</script>
{% endblock %}

mainApp/templates/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Employee Data Collation App | Employee List</title>

  <!-- start: Css -->
  <link rel="stylesheet" type="text/css" href="{% static 'asset/css/bootstrap.min.css' %}">

  <!-- plugins -->
  <link rel="stylesheet" type="text/css" href="{% static 'asset/css/plugins/font-awesome.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'asset/css/plugins/datatables.bootstrap.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'asset/css/plugins/animate.min.css' %}"/>
  <link href="{% static 'asset/css/style.css' %}" rel="stylesheet">
  
 
   {% block css %} {% endblock %}
 

<body id="mimin" class="dashboard">
      <!-- start: Header -->
        <nav class="navbar navbar-default header navbar-fixed-top">
          <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
              <div class="opener-left-menu is-open">
                <span class="top"></span>
                <span class="middle"></span>
                <span class="bottom"></span>
              </div>
                <a href="/" class="navbar-brand"> 
                 <b>Employee Data Collation App</b>
                </a>

            </div>
          </div>
        </nav>
      <!-- end: Header -->

      <div class="container-fluid mimin-wrapper">
  
          <!-- start:Left Menu -->
            <div id="left-menu">
              <div class="sub-left-menu scroll">
                <ul class="nav nav-list">
                    <li><div class="left-bg"></div></li>
                    <li class="time">
                      <h1 class="animated fadeInLeft">21:00</h1>
                      <p class="animated fadeInRight">Sat,October 1st 2029</p>
                    </li>

                    <li class="{% block dashboardActive %}  {% endblock %} ripple">
                      <a class="tree-toggle nav-header"><span class="fa-home fa"></span> Dashboard 
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                          <li><a href="/">List of Employees</a></li>
                          <li><a href="{% url 'mainApp:add-employee' %}">Manually Add Employee</a></li>
                      </ul>
                    </li>
                    <li class="{% block uploadActive %}  {% endblock %} ripple">
                      <a class="tree-toggle nav-header">
                        <span class="fa-cloud fa"></span> Upload
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                        <li><a href="{% url 'mainApp:upload-excel' %}">Excel Add Employee</a></li>
                        <li><a href="{% url 'mainApp:logs-employees' %}">Logs/List</a></li>
                      </ul>
                    </li>
                    
                    <li>
                      <a href="{% url 'mainApp:logout' %}" style="color:red">
                        Logout
                      </a>
                    </li>

                  </ul>
                </div>
            </div>
          <!-- end: Left Menu -->

          {% block content %} {% endblock %}


             
          
      </div>

      <!-- start: Mobile -->
      <div id="mimin-mobile" class="reverse">
        <div class="mimin-mobile-menu-list">
            <div class="col-md-12 sub-mimin-mobile-menu-list animated fadeInLeft">
                <ul class="nav nav-list">
                    <li class="active ripple">
                      <a class="tree-toggle nav-header">
                        <span class="fa-home fa"></span>Dashboard 
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                          <li><a href="#">List of Employees </a></li>
                          <li><a href="#">Employees logs</a></li>
                      </ul>
                    </li>
                    <li class="ripple">
                      <a class="tree-toggle nav-header">
                        <span class="fa-cloud fa"></span> Upload
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                        <li><a href="#">Upload employee data</a></li>
                        <li><a href="#">Add an employee</a></li>
                      </ul>
                    </li>
                    
                  </ul>
            </div>
        </div>       
      </div>
      <button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
        <span class="fa fa-bars"></span>
      </button>
       <!-- end: Mobile -->

<!-- start: Javascript -->
<script src="{% static 'asset/js/jquery.min.js' %}"></script>
<script src="{% static 'asset/js/jquery.ui.min.js' %}"></script>
<script src="{% static 'asset/js/bootstrap.min.js' %}"></script>



<!-- plugins -->
<script src="{% static 'asset/js/plugins/moment.min.js' %}"></script>
<script src="{% static 'asset/js/plugins/jquery.datatables.min.js' %}"></script>
<script src="{% static 'asset/js/plugins/datatables.bootstrap.min.js' %}"></script>
<script src="{% static 'asset/js/plugins/jquery.nicescroll.js' %}"></script>


<!-- custom -->
<script src="{% static 'asset/js/main.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $('#datatables-example').DataTable();
  });
</script>
{% block javascript %} {% endblock %}

<!-- plugins -->






<!-- end: Javascript -->
</body>
</html>

mainApp/templates/employee-list.html
{% extends 'base.html' %}
{% load static %}
{% block dashboardActive %}  active {% endblock %}
{% block content %}
            <!-- start: Content -->
            <div id="content">
               <div class="panel box-shadow-none content-header">
                  <div class="panel-body">
                    <div class="col-md-12">
                        <h3 class="animated fadeInLeft">Employee List</h3>
                        <p class="animated fadeInDown">
                          List of employees and associated attributes
                        </p>
                    </div>
                  </div>
              </div>
              <div class="col-md-12 top-20 padding-0">
                <div class="col-md-12">
                  <div class="panel">
                    <div class="panel-body">
                      <div class="responsive-table">
                      <table id="datatables-example" class="table table-striped table-bordered" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th>First Name</th>
                          <th>Middle Name</th>
                          <th>Date of graduation</th>
                          <th>Date of employment</th>
                          <th>Position</th>
                          <th>Salary</th>
                          <th>Supervisors</th>
                          <th>Employee Code</th>
                         
                        </tr>
                      </thead>
                      <tbody>
                        {% for employer in employees %}
                        <tr>
                          <td>{{employer.first_name}}</td>
                          <td>{{employer.middle_name}}</td>
                          <td>{{employer.date_of_graduation}}</td>
                          <td>{{employer.date_of_employment}}</td>
                          <td>{{employer.position}}</td>
                          <td>${{employer.salary}}</td>
                          <td>
                            {% for supervisor in employer.supervisors.all %}
                                {{supervisor}}<br>
                            {% empty %}
                                 ---
                            {% endfor %}
                          </td>
                          <td>{{employer.employee_code}}</td>

                        </tr>
                        {% endfor %}

                                               
                      </tbody>
                        </table>
                      </div>
                  </div>
                </div>
              </div>  
              </div>
            </div>
          <!-- end: content -->

{% endblock %}

   

mainApp/templates/employee-logs.html
{% extends 'base.html' %}
{% load static %}
{% block uploadActive %}active  {% endblock %}
{% block content %}
            <!-- start: Content -->
            <div id="content">
               <div class="panel box-shadow-none content-header">
                  <div class="panel-body">
                    <div class="col-md-12">
                        <h3 class="animated fadeInLeft">Upload logs</h3>
                        <p class="animated fadeInDown">
                          Logs/List of all uploads
                        </p>
                    </div>
                  </div>
              </div>
              <div class="col-md-12 top-20 padding-0">
                <div class="col-md-12">
                  <div class="panel">
                    <div class="panel-body">
                      <div class="responsive-table">
                      <table id="datatables-example" class="table table-striped table-bordered" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th>Name of employee</th>
                          <th>Employee code</th>
                          <th>Time uploaded</th>
                          <th>Employee records uploaded</th>
                          <th>Status</th>
                          <th>Errors</th>
                         
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>First name</td>
                          <td>middle namet</td>
                          <td>date of graduation</td>
                          <td>Date of employment</td>
                          <td>Position</td>
                          <td>$Salary</td>
                          
                        </tr>
                                               
                      </tbody>
                        </table>
                      </div>
                  </div>
                </div>
              </div>  
              </div>
            </div>
          <!-- end: content -->

{% endblock %}
                
   